kind: Deployment
apiVersion: apps/v1
metadata:
  name: agentic-app-be
  labels:
    app: agentic-app-be
    app.kubernetes.io/component: agentic-app-be
    app.kubernetes.io/instance: agentic-app-be
    app.kubernetes.io/name: agentic-app-be
    app.kubernetes.io/part-of: agentic-app-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-app-be
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: agentic-app-be
        deployment: agentic-app-be
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: agentic-app-be
          image: quay.io/rcarrata/agentic-app-be:v1
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: agentic-app-be-secret
                  key: API_KEY
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: agentic-app-be-secret
                  key: API_URL
            - name: MODEL_NAME
              valueFrom:
                secretKeyRef:
                  name: agentic-app-be-secret
                  key: MODEL_NAME
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600